FROM python:3.10-slim

COPY ./requirements.txt /fastapi_app/requirements.txt

WORKDIR fastapi_app 

RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./app /fastapi_app/app

CMD uvicorn --app-dir=app --host=0.0.0.0 --port=${APP_PORT_DOCKER} --reload \
app:app
