services:
  fastapi_app:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile_app
    ports:
      - ${HOST_EXTERNAL}:${APP_PORT_EXTERNAL}:${APP_PORT_DOCKER}
    volumes:
      - ./models:/fastapi_app/models
    hostname: fastapi_app

  prometheus:
    image: prom/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=${PROMETHEUS_LOG_LEVEL}'
    ports:
      - ${HOST_EXTERNAL}:${PROMETHEUS_PORT_EXTERNAL}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    hostname: prometheus

  grafana:
    image: grafana/grafana
    ports:
      - ${HOST_EXTERNAL}:${GRAFANA_PORT_EXTERNAL}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_USER_PASSWORD}
      - GF_LOG_LEVEL=${GRAFANA_LOG_LEVEL}

    hostname: grafana
