{
 "title": "dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests rate vs unhndled exceptions rate [1/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\"}[1m])",
     "legendFormat": "Prediction requests rate"
    },
    {
     "expr": "rate(app_prediction_exception_counter_total{}[1m])",
     "legendFormat": "Unhandled exceptions rate"
    }
   ]
  },
  {
   "title": "Model predicitons (mlnRub)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "delta(app_prediction_values_sum[5m]) / delta(app_prediction_values_count[5m])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.5, delta(app_prediction_values_bucket[5m]))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.95, delta(app_prediction_values_bucket[5m]))",
     "legendFormat": "95% quantile"
    },
    {
     "expr": "histogram_quantile(0.05, delta(app_prediction_values_bucket[5m]))",
     "legendFormat": "5% quantile"
    }
   ]
  },
  {
   "title": "Response latency [1m avg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_sum{handler=\"/predict\"}[1m]) / increase(http_request_duration_seconds_count{handler=\"/predict\"}[1m])",
     "legendFormat": "Avearge response latency (1m avearge)"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"fastapi_app:7000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU time (per second)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total exceptions unhandled",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_prediction_exception_counter_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}